export const acceptableCurrencies = [
  {
      "currencyId": 1,
      "name": "Tether",
      "symbol": "USDT",
      "isFiat": false,
      "isNative": false,
      "chainId": 11155111,
      "tokenContract": "0xEF6fF1e5D9e2B3AfB2bE16f2176b8404B123DddB",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/tether28_2.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 2
  },
  {
      "currencyId": 2,
      "name": "USD Coin",
      "symbol": "USDC",
      "isFiat": false,
      "isNative": false,
      "chainId": 11155111,
      "tokenContract": "0x90410dAc25c10b87D4ea49CA196894156dA410D8",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/centre-usdc_28.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 2
  },
  {
      "currencyId": 1005,
      "name": "Sepolia Ether",
      "symbol": "ETH",
      "isFiat": false,
      "isNative": true,
      "chainId": 11155111,
      "tokenContract": "",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://icons.llamao.fi/icons/chains/rsz_ethereum.jpg",
      "decimals": 18,
      "conversionRate": 2785.95,
      "rounding": 6
  },
  {
      "currencyId": 1006,
      "name": "Polygon",
      "symbol": "MATIC",
      "isFiat": false,
      "isNative": true,
      "chainId": 80002,
      "tokenContract": "",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://icons.llamao.fi/icons/chains/rsz_polygon.jpg",
      "decimals": 18,
      "conversionRate": 0.2919,
      "rounding": 6
  },
  {
      "currencyId": 1007,
      "name": "Arbitrum",
      "symbol": "ARB",
      "isFiat": false,
      "isNative": true,
      "chainId": 421614,
      "tokenContract": "",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://icons.llamao.fi/icons/chains/rsz_arbitrum.jpg",
      "decimals": 18,
      "conversionRate": 0.4713,
      "rounding": 6
  },
  {
      "currencyId": 1008,
      "name": "Optimism",
      "symbol": "OP",
      "isFiat": false,
      "isNative": true,
      "chainId": 11155420,
      "tokenContract": "",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://optimistic.etherscan.io/assets/optimism/images/svg/logos/token-secondary-light.svg",
      "decimals": 18,
      "conversionRate": 1.1659,
      "rounding": 6
  },
  {
      "currencyId": 1009,
      "name": "Tether",
      "symbol": "USDT",
      "isFiat": false,
      "isNative": false,
      "chainId": 80002,
      "tokenContract": "0xEF6fF1e5D9e2B3AfB2bE16f2176b8404B123DddB",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/tether28_2.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 2
  },
  {
      "currencyId": 1010,
      "name": "Ether",
      "symbol": "ETH",
      "isFiat": false,
      "isNative": true,
      "chainId": 1,
      "tokenContract": "",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://icons.llamao.fi/icons/chains/rsz_ethereum.jpg",
      "decimals": 18,
      "conversionRate": 2785.95,
      "rounding": 6
  },
  {
      "currencyId": 1011,
      "name": "Tether",
      "symbol": "USDT",
      "isFiat": false,
      "isNative": false,
      "chainId": 421614,
      "tokenContract": "0xEF6fF1e5D9e2B3AfB2bE16f2176b8404B123DddB",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/tether28_2.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 2
  },
  {
      "currencyId": 1012,
      "name": "USD Coin",
      "symbol": "USDC",
      "isFiat": false,
      "isNative": false,
      "chainId": 80002,
      "tokenContract": "0x90410dAc25c10b87D4ea49CA196894156dA410D8",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/centre-usdc_28.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 2
  },
  {
      "currencyId": 1013,
      "name": "USD Coin",
      "symbol": "USDC",
      "isFiat": false,
      "isNative": false,
      "chainId": 421614,
      "tokenContract": "0xf48F8E8a7a823d9D2bB429d833Cf4Ce1eD4258D4",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/centre-usdc_28.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 2
  },
  {
      "currencyId": 1014,
      "name": "USD Coin",
      "symbol": "USDC",
      "isFiat": false,
      "isNative": false,
      "chainId": 11155420,
      "tokenContract": "0x90410dAc25c10b87D4ea49CA196894156dA410D8",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/centre-usdc_28.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 2
  },
  {
      "currencyId": 1015,
      "name": "Tether",
      "symbol": "USDT",
      "isFiat": false,
      "isNative": false,
      "chainId": 11155420,
      "tokenContract": "0xEF6fF1e5D9e2B3AfB2bE16f2176b8404B123DddB",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/tether28_2.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 2
  },
  {
      "currencyId": 1016,
      "name": "Base Ether",
      "symbol": "ETH",
      "isFiat": false,
      "isNative": true,
      "chainId": 84532,
      "tokenContract": "",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://icons.llamao.fi/icons/chains/rsz_base.jpg",
      "decimals": 18,
      "conversionRate": 2785.95,
      "rounding": 6
  },
  {
      "currencyId": 1017,
      "name": "USD Coin",
      "symbol": "USDC",
      "isFiat": false,
      "isNative": true,
      "chainId": 84532,
      "tokenContract": "0x4fCF2d9f0583e7dB7e3Eb6A2b9eD8f4Ac3BfB634",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/centre-usdc_28.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 6
  },
  {
      "currencyId": 1018,
      "name": "Tether",
      "symbol": "USDT",
      "isFiat": false,
      "isNative": true,
      "chainId": 84532,
      "tokenContract": "0x6D15723FA5dce808513550503697f9C66a9159B6",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/tether28_2.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 6
  },
  {
      "currencyId": 1019,
      "name": "Tether",
      "symbol": "USDT",
      "isFiat": false,
      "isNative": false,
      "chainId": 1,
      "tokenContract": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/tether28_2.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 2
  },
  {
      "currencyId": 1020,
      "name": "USD Coin",
      "symbol": "USDC",
      "isFiat": false,
      "isNative": false,
      "chainId": 1,
      "tokenContract": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "depositConfirmations": 6,
      "liquidationConfirmations": 12,
      "icon": "https://etherscan.io/token/images/centre-usdc_28.png",
      "decimals": 6,
      "conversionRate": 1,
      "rounding": 2
  }
]